# Generated by Django 5.2.1 on 2025-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
