# Generated by Django 5.2.1 on 2025-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=''),
        ),
    ]
